[project]
name = "sana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "authlib>=1.6.5",
    "pydantic-settings>=2.11.0",
]

[tool.uv.workspace]
members = ["app", "infra", "sana"]
