AWSTemplateFormatVersion: '2010-09-09'
Description: AWS

Resources:
  Gateway:
    Type: AWS::BedrockAgentCore::Gateway
    Properties:
      Name: sana
      Description: MCP Gateway for Sana application
      RoleArn: 
      AuthorizerType: CUSTOM_JWT
      AuthorizerConfiguration:
        CustomJWTAuthorizer:
          DiscoveryUrl: !Join 
            - ""
            - - https://
              - !Ref AWS::Region
              - .amazonaws.com
              - !ImportValue Sana-UserPoolId
              - /.well-known/openid-configuration
          AllowedClients:
            - !ImportValue Sana-UserPoolClientId
      ProtocolType: MCP

  SearchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: sana-search
      Runtime: python3.13
      Handler: main.handler
      Role: 
      Code:
        ZipFile: |

      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          

  SearchTarget:
    Type: AWS::BedrockAgentCore::GatewayTarget
    Properties:
      Name: sana-search-target
      Description: Search target for the Sana application
      GatewayIdentifier: !Ref Gateway
      TargetConfiguration:
        Mcp:
          Lambda:
            LambdaArn: !GetAtt SearchFunction.Arn
            ToolSchema:
              InlinePayload:
                - Name: searchProducts
                  Description: Searches for products based on keywords
                  InputSchema:
                    Type: object
                    Properties:
                      keywords:
                        type: string
                        description: Search keywords
                    Required:
                      - keywords


