AWSTemplateFormatVersion: '2010-09-09'
Description: AWS

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: sana-user-pool
      MfaConfiguration: "OFF"
      UsernameConfiguration:
        CaseSensitive: false
      UsernameAttributes: 
        - email
      AutoVerifiedAttributes: 
        - email
    
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: sana
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      SupportedIdentityProviders: 
        - COGNITO
      AllowedOAuthScopes: 
        - openid
        - email
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: 
        - code
      CallbackURLs: 
        - http://localhost:8501/
      LogoutURLs: 
        - http://localhost:8501/
      EnableTokenRevocation: true
      AccessTokenValidity: 60
      RefreshTokenValidity: 60
      IdTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
    
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join
        - sana-
        - !Ref AWS::AccountId

  UserPoolClientParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sana/auth/client-id
      Description: Client identifier for the Sana application user pool
      Type: String
      Value: !Ref UserPoolClient

  UserPoolDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sana/auth/domain
      Description: Domain for the Sana application user pool
      Type: String
      Value: !Join 
        - https://
        - !GetAtt UserPoolDomain.Domain
  
Outputs:
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Value: !Ref UserPool
    Export:
      Name: Sana-UserPoolId

  UserPoolClientId:
    Description: The ID of the Cognito User Pool Client
    Value: !Ref UserPoolClient
    Export:
      Name: Sana-UserPoolClientId