[theme]
primaryColor = "#babca1"
backgroundColor = "#f4f3ed"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.6rem"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
headingFontSizes = ["40px", "32px", "24px"]
headingFontWeights = [300, 400]

[theme.sidebar]
backgroundColor = "#e8e7dd"
secondaryBackgroundColor = "#ecebe3"
